@startuml "ModelSessionsDiagram"

class "Session" as sessionClass {
    +{field} title: string
    +{field} model: string
}
class "SessionManager" as sessionManagerClass {
    -{field} sessions: map<string, Session>
    -{field} currentSession: Session
    +{field} sessionTitle: string
    +{field} sessionModel: string
    +{method} createNewSession(title: string): string
    +{method} selectNewSession(title: string): string
    +{method} changeSessionTitle(title: string): string
}

sessionManagerClass o-- sessionClass : " use"

@enduml